[build]
    publish = "public"
    command = "npm run build"
[build.environment]
    NODE_VERSION = "18.2.0"
    NETLIFY_USE_YARN = "false"
    GATSBY_CONCURRENT_DOWNLOAD = "16"
    GATSBY_CPU_COUNT = "2"